"""add_analytics_fields_and_detection_log

Revision ID: 4e6a95b21bdf
Revises: 1ee74a36e46c
Create Date: 2026-03-16 18:17:42.343480
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6a95b21bdf'
down_revision: Union[str, None] = '1ee74a36e46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_estimate', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('mood_confidence', sa.Float(), nullable=True),
    sa.Column('bbox_x', sa.Integer(), nullable=True),
    sa.Column('bbox_y', sa.Integer(), nullable=True),
    sa.Column('bbox_w', sa.Integer(), nullable=True),
    sa.Column('bbox_h', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mood_logs', sa.Column('zone', sa.String(length=20), nullable=False))
    op.add_column('visitors', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('visitors', sa.Column('age_estimate', sa.Integer(), nullable=True))
    op.add_column('visitors', sa.Column('age_group', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'age_group')
    op.drop_column('visitors', 'age_estimate')
    op.drop_column('visitors', 'gender')
    op.drop_column('mood_logs', 'zone')
    op.drop_table('detection_logs')
    # ### end Alembic commands ###
